"""Workout-Daten für den Timer – basierend auf workout.md."""

WORKOUT_DATA = {
    "w1t1": {
        "name": "Odin – Kraft & Kontrolle",
        "steps": [
            {"name": "Leichte Swings", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Halos", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Cat-Cow", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Goblet Squats (ohne Gewicht)", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Leichte Mobilität", "detail": "Warm-up abschließen", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "5 Turkish Get-Ups (links)", "detail": "Runde 1/3 – langsam, qualitativ", "duration": 90, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "5 Turkish Get-Ups (rechts)", "detail": "Runde 1/3", "duration": 90, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "6 Clean & Press (links)", "detail": "Runde 1/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "6 Clean & Press (rechts)", "detail": "Runde 1/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "12 Swings", "detail": "Runde 1/3", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "60-90 Sekunden Erholung", "duration": 75, "phase": "⚔️ HAUPTTEIL"},
            {"name": "5 Turkish Get-Ups (links)", "detail": "Runde 2/3", "duration": 90, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "5 Turkish Get-Ups (rechts)", "detail": "Runde 2/3", "duration": 90, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "6 Clean & Press (links)", "detail": "Runde 2/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "6 Clean & Press (rechts)", "detail": "Runde 2/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "12 Swings", "detail": "Runde 2/3", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "60-90 Sekunden Erholung", "duration": 75, "phase": "⚔️ HAUPTTEIL"},
            {"name": "5 Turkish Get-Ups (links)", "detail": "Runde 3/3", "duration": 90, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "5 Turkish Get-Ups (rechts)", "detail": "Runde 3/3", "duration": 90, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "6 Clean & Press (links)", "detail": "Runde 3/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "6 Clean & Press (rechts)", "detail": "Runde 3/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "12 Swings", "detail": "Runde 3/3", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Goblet Squats", "detail": "Zusatz Runde 1/3", "duration": 60, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "10 Sek Plank", "detail": "Zusatz Runde 1/3 – Bauch", "duration": 30, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "10 Goblet Squats", "detail": "Zusatz Runde 2/3", "duration": 60, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "10 Sek Plank", "detail": "Zusatz Runde 2/3", "duration": 30, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "10 Goblet Squats", "detail": "Zusatz Runde 3/3", "duration": 60, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "10 Sek Plank", "detail": "Zusatz Runde 3/3", "duration": 30, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft! Atme durch.", "duration": 120, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w1t2": {
        "name": "Thor – Power & Ausdauer",
        "steps": [
            {"name": "Hüftbeugen", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Kniebeugen", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Schultermobilität", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Leichte Bewegung", "detail": "Warm-up abschließen", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Mobilität", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "15 Swings", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "10 Goblet Squats", "detail": "Runde 1/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Push-Press (links)", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Push-Press (rechts)", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "45-75 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "15 Swings", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "10 Goblet Squats", "detail": "Runde 2/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Push-Press (links)", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Push-Press (rechts)", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "45-75 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "15 Swings", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "10 Goblet Squats", "detail": "Runde 3/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Push-Press (links)", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Push-Press (rechts)", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "45-75 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "15 Swings", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "10 Goblet Squats", "detail": "Runde 4/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Push-Press (links)", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Push-Press (rechts)", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "15 Swings (leicht, schnell)", "detail": "Zusatz Runde 1/3", "duration": 40, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "15 Swings (leicht, schnell)", "detail": "Zusatz Runde 2/3", "duration": 40, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "15 Swings (leicht, schnell)", "detail": "Zusatz Runde 3/3", "duration": 40, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 120, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w1t3": {
        "name": "Freya – Mobilität & Ganzkörper",
        "steps": [
            {"name": "Armkreise", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Halos", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Seitliche Goblet-Lunges", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Leichte Mobilität", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Dynamisches Dehnen", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "10 Halos", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "8 Reverse Lunges (links)", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "8 Reverse Lunges (rechts)", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "10 Floor-Press (links)", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "10 Floor-Press (rechts)", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "10 Halos", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "8 Reverse Lunges (links)", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "8 Reverse Lunges (rechts)", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "10 Floor-Press (links)", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "10 Floor-Press (rechts)", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "10 Halos", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "8 Reverse Lunges (links)", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "8 Reverse Lunges (rechts)", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Floor-Press (links)", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Floor-Press (rechts)", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "15 Goblet Squats", "detail": "Zusatz 1/3", "duration": 60, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "20 Sek Hüftbeugen", "detail": "Zusatz 1/3", "duration": 40, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "15 Goblet Squats", "detail": "Zusatz 2/3", "duration": 60, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "20 Sek Hüftbeugen", "detail": "Zusatz 2/3", "duration": 40, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "15 Goblet Squats", "detail": "Zusatz 3/3", "duration": 60, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "20 Sek Hüftbeugen", "detail": "Zusatz 3/3", "duration": 40, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 120, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w2t1": {
        "name": "Loki – Explosiv & Kreativ",
        "steps": [
            {"name": "Kniebeugen hoch (Sprungseil-Ersatz)", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Sprung-Alternativen", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Leichter Swingtest", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Mobilität", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "6 Snatches (links)", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "6 Snatches (rechts)", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Front-Rack-Lunges (links)", "detail": "Runde 1/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Front-Rack-Lunges (rechts)", "detail": "Runde 1/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Renegade-Rows (links)", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Renegade-Rows (rechts)", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "60-90 Sekunden", "duration": 75, "phase": "⚔️ HAUPTTEIL"},
            {"name": "6 Snatches (links)", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "6 Snatches (rechts)", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Front-Rack-Lunges (links)", "detail": "Runde 2/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Front-Rack-Lunges (rechts)", "detail": "Runde 2/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Renegade-Rows (links)", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Renegade-Rows (rechts)", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "60-90 Sekunden", "duration": 75, "phase": "⚔️ HAUPTTEIL"},
            {"name": "6 Snatches (links)", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "6 Snatches (rechts)", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Front-Rack-Lunges (links)", "detail": "Runde 3/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Front-Rack-Lunges (rechts)", "detail": "Runde 3/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Renegade-Rows (links)", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Renegade-Rows (rechts)", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "60-90 Sekunden", "duration": 75, "phase": "⚔️ HAUPTTEIL"},
            {"name": "6 Snatches (links)", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "6 Snatches (rechts)", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Front-Rack-Lunges (links)", "detail": "Runde 4/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Front-Rack-Lunges (rechts)", "detail": "Runde 4/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Renegade-Rows (links)", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Renegade-Rows (rechts)", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 1/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 2/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 3/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 120, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w2t2": {
        "name": "Tyr – Starker Basis-Typ",
        "steps": [
            {"name": "Hüfte mobilisieren", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Schulter mobilisieren", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Leichter Goblet Squat", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Allgemeine Mobilität", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "8 Deadlifts", "detail": "Runde 1/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Strict Press (links)", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Strict Press (rechts)", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "10 Goblet Squats", "detail": "Runde 1/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "8 Deadlifts", "detail": "Runde 2/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Strict Press (links)", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Strict Press (rechts)", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "10 Goblet Squats", "detail": "Runde 2/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "8 Deadlifts", "detail": "Runde 3/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Strict Press (links)", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Strict Press (rechts)", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "10 Goblet Squats", "detail": "Runde 3/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "8 Deadlifts", "detail": "Runde 4/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Strict Press (links)", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Strict Press (rechts)", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "10 Goblet Squats", "detail": "Runde 4/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "10 Swings + 10 Front Squats", "detail": "Zusatz 1/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "10 Swings + 10 Front Squats", "detail": "Zusatz 2/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "10 Swings + 10 Front Squats", "detail": "Zusatz 3/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 120, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w2t3": {
        "name": "Heimdall – Ganzkörper-Flow",
        "steps": [
            {"name": "Arm-Mobilisation", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Hüft-Mobilisation", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Leichte Bewegung", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Dynamisches Dehnen", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "10 Swings", "detail": "Runde 1/3", "duration": 40, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "10 Windmills (links)", "detail": "Runde 1/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "10 Windmills (rechts)", "detail": "Runde 1/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "Carries (links, 20-30m)", "detail": "Runde 1/3", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "Carries (rechts, 20-30m)", "detail": "Runde 1/3", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "60-90 Sekunden", "duration": 75, "phase": "⚔️ HAUPTTEIL"},
            {"name": "10 Swings", "detail": "Runde 2/3", "duration": 40, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "10 Windmills (links)", "detail": "Runde 2/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "10 Windmills (rechts)", "detail": "Runde 2/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "Carries (links, 20-30m)", "detail": "Runde 2/3", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "Carries (rechts, 20-30m)", "detail": "Runde 2/3", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "60-90 Sekunden", "duration": 75, "phase": "⚔️ HAUPTTEIL"},
            {"name": "10 Swings", "detail": "Runde 3/3", "duration": 40, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Windmills (links)", "detail": "Runde 3/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Windmills (rechts)", "detail": "Runde 3/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "Carries (links, 20-30m)", "detail": "Runde 3/3", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "Carries (rechts, 20-30m)", "detail": "Runde 3/3", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Goblet Squats + 10 Swings", "detail": "Zusatz 1/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "10 Goblet Squats + 10 Swings", "detail": "Zusatz 2/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "10 Goblet Squats + 10 Swings", "detail": "Zusatz 3/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 120, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w3t1": {
        "name": "Valkyrie – Intervall-Krieger",
        "steps": [
            {"name": "Sprung-Übungen", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Leichter Swing", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Armkreise", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Mobilität", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "30 Sek Swings", "detail": "Runde 1/5 – Vollgas!", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 5},
            {"name": "30 Sek Squats (mit Kugel)", "detail": "Runde 1/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 5},
            {"name": "30 Sek High Pulls", "detail": "Runde 1/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 5},
            {"name": "⏸ Pause", "detail": "30 Sekunden", "duration": 30, "phase": "⚔️ HAUPTTEIL"},
            {"name": "30 Sek Swings", "detail": "Runde 2/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 5},
            {"name": "30 Sek Squats (mit Kugel)", "detail": "Runde 2/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 5},
            {"name": "30 Sek High Pulls", "detail": "Runde 2/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 5},
            {"name": "⏸ Pause", "detail": "30 Sekunden", "duration": 30, "phase": "⚔️ HAUPTTEIL"},
            {"name": "30 Sek Swings", "detail": "Runde 3/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 5},
            {"name": "30 Sek Squats (mit Kugel)", "detail": "Runde 3/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 5},
            {"name": "30 Sek High Pulls", "detail": "Runde 3/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 5},
            {"name": "⏸ Pause", "detail": "30 Sekunden", "duration": 30, "phase": "⚔️ HAUPTTEIL"},
            {"name": "30 Sek Swings", "detail": "Runde 4/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 5},
            {"name": "30 Sek Squats (mit Kugel)", "detail": "Runde 4/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 5},
            {"name": "30 Sek High Pulls", "detail": "Runde 4/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 5},
            {"name": "⏸ Pause", "detail": "30 Sekunden", "duration": 30, "phase": "⚔️ HAUPTTEIL"},
            {"name": "30 Sek Swings", "detail": "Runde 5/5 – Letzte Runde!", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 5, "totalRounds": 5},
            {"name": "30 Sek Squats (mit Kugel)", "detail": "Runde 5/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 5, "totalRounds": 5},
            {"name": "30 Sek High Pulls", "detail": "Runde 5/5", "duration": 30, "phase": "⚔️ HAUPTTEIL", "round": 5, "totalRounds": 5},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 1/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 2/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 3/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 180, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w3t2": {
        "name": "Baldr – Technik & Kontrolle",
        "steps": [
            {"name": "Halos", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Leichte Clean-Übungen", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Mobilität", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Leichte Bewegung", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "8 Halos", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "6 Clean & Press (links)", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "6 Clean & Press (rechts)", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "8 Goblet Squats", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "8 Halos", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "6 Clean & Press (links)", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "6 Clean & Press (rechts)", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "8 Goblet Squats", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "8 Halos", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "6 Clean & Press (links)", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "6 Clean & Press (rechts)", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "8 Goblet Squats", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 1/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 2/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 3/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 180, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w3t3": {
        "name": "Thor (verstärkt)",
        "steps": [
            {"name": "Hüfte mobilisieren", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Schulter mobilisieren", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Leichte Swings", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Mobilität", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "20 Swings", "detail": "Runde 1/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "12 Goblet Squats", "detail": "Runde 1/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "10 Push-Press (links)", "detail": "Runde 1/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "10 Push-Press (rechts)", "detail": "Runde 1/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "45-75 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "20 Swings", "detail": "Runde 2/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "12 Goblet Squats", "detail": "Runde 2/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "10 Push-Press (links)", "detail": "Runde 2/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "10 Push-Press (rechts)", "detail": "Runde 2/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "45-75 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "20 Swings", "detail": "Runde 3/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "12 Goblet Squats", "detail": "Runde 3/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "10 Push-Press (links)", "detail": "Runde 3/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "10 Push-Press (rechts)", "detail": "Runde 3/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "45-75 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "20 Swings", "detail": "Runde 4/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "12 Goblet Squats", "detail": "Runde 4/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "10 Push-Press (links)", "detail": "Runde 4/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "10 Push-Press (rechts)", "detail": "Runde 4/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "15 Swings + 10 Goblet Squats", "detail": "Zusatz 1/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "15 Swings + 10 Goblet Squats", "detail": "Zusatz 2/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "15 Swings + 10 Goblet Squats", "detail": "Zusatz 3/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 120, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w4t1": {
        "name": "Odin (verfeinert)",
        "steps": [
            {"name": "Leichte Swings", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Halos", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Cat-Cow", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Goblet Squats (leicht)", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "Mobilität", "detail": "Warm-up", "duration": 120, "phase": "🔥 WARM-UP"},
            {"name": "4 Turkish Get-Ups (links)", "detail": "Runde 1/3", "duration": 80, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "4 Turkish Get-Ups (rechts)", "detail": "Runde 1/3", "duration": 80, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "8 Clean & Press (links)", "detail": "Runde 1/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "8 Clean & Press (rechts)", "detail": "Runde 1/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "10 Swings", "detail": "Runde 1/3", "duration": 40, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "90 Sekunden", "duration": 90, "phase": "⚔️ HAUPTTEIL"},
            {"name": "4 Turkish Get-Ups (links)", "detail": "Runde 2/3", "duration": 80, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "4 Turkish Get-Ups (rechts)", "detail": "Runde 2/3", "duration": 80, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "8 Clean & Press (links)", "detail": "Runde 2/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "8 Clean & Press (rechts)", "detail": "Runde 2/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "10 Swings", "detail": "Runde 2/3", "duration": 40, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "90 Sekunden", "duration": 90, "phase": "⚔️ HAUPTTEIL"},
            {"name": "4 Turkish Get-Ups (links)", "detail": "Runde 3/3", "duration": 80, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "4 Turkish Get-Ups (rechts)", "detail": "Runde 3/3", "duration": 80, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "8 Clean & Press (links)", "detail": "Runde 3/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "8 Clean & Press (rechts)", "detail": "Runde 3/3", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Swings", "detail": "Runde 3/3", "duration": 40, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Goblet Squats + 10 Swings", "detail": "Zusatz 1/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "10 Goblet Squats + 10 Swings", "detail": "Zusatz 2/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "10 Goblet Squats + 10 Swings", "detail": "Zusatz 3/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 120, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w4t2": {
        "name": "Loki (verstärkt)",
        "steps": [
            {"name": "Kniebeugen hoch", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Sprung-Alternativen", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Leichter Swingtest", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Mobilität", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "8 Snatches (links)", "detail": "Runde 1/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Snatches (rechts)", "detail": "Runde 1/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Rows (links)", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Rows (rechts)", "detail": "Runde 1/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "8 Front-Rack-Squats", "detail": "Runde 1/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "8 Snatches (links)", "detail": "Runde 2/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Snatches (rechts)", "detail": "Runde 2/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Rows (links)", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Rows (rechts)", "detail": "Runde 2/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "8 Front-Rack-Squats", "detail": "Runde 2/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "8 Snatches (links)", "detail": "Runde 3/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Snatches (rechts)", "detail": "Runde 3/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Rows (links)", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Rows (rechts)", "detail": "Runde 3/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "8 Front-Rack-Squats", "detail": "Runde 3/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 4},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "8 Snatches (links)", "detail": "Runde 4/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Snatches (rechts)", "detail": "Runde 4/4", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Rows (links)", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Rows (rechts)", "detail": "Runde 4/4", "duration": 45, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "8 Front-Rack-Squats", "detail": "Runde 4/4", "duration": 60, "phase": "⚔️ HAUPTTEIL", "round": 4, "totalRounds": 4},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 1/3 (leicht)", "duration": 80, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 2/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "10 Swings + 10 Goblet Squats", "detail": "Zusatz 3/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 120, "phase": "🧘 COOL-DOWN"},
        ]
    },
    "w4t3": {
        "name": "Freya (verfeinert)",
        "steps": [
            {"name": "Leichte Mobilitätsübungen", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Armkreise", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Halos", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "Dynamisches Dehnen", "detail": "Warm-up", "duration": 150, "phase": "🔥 WARM-UP"},
            {"name": "12 Halos", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "8 Lunges (links)", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "8 Lunges (rechts)", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "10 Floor-Press (links)", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "10 Floor-Press (rechts)", "detail": "Runde 1/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 1, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "12 Halos", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "8 Lunges (links)", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "8 Lunges (rechts)", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "10 Floor-Press (links)", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "10 Floor-Press (rechts)", "detail": "Runde 2/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 2, "totalRounds": 3},
            {"name": "⏸ Pause", "detail": "60 Sekunden", "duration": 60, "phase": "⚔️ HAUPTTEIL"},
            {"name": "12 Halos", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "8 Lunges (links)", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "8 Lunges (rechts)", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Floor-Press (links)", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Floor-Press (rechts)", "detail": "Runde 3/3", "duration": 50, "phase": "⚔️ HAUPTTEIL", "round": 3, "totalRounds": 3},
            {"name": "10 Goblet Squats + 10 Swings", "detail": "Zusatz 1/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 1, "totalRounds": 3},
            {"name": "10 Goblet Squats + 10 Swings", "detail": "Zusatz 2/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 2, "totalRounds": 3},
            {"name": "10 Goblet Squats + 10 Swings", "detail": "Zusatz 3/3", "duration": 80, "phase": "💪 ZUSATZ", "round": 3, "totalRounds": 3},
            {"name": "Cool-down & Dehnen", "detail": "Geschafft!", "duration": 120, "phase": "🧘 COOL-DOWN"},
        ]
    },
}
